//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Message
{
	public virtual object Subject
	{
		get;
		set;
	}

	public virtual object Body
	{
		get;
		set;
	}

	public virtual object Date
	{
		get;
		set;
	}

	public virtual object To
	{
		get;
		set;
	}

	public virtual object From
	{
		get;
		set;
	}

}

